# For more information about the available options please visit: http://go/backstage (VPN required)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: unity/com.unity.cloud.draco
  name: com.unity.cloud.draco
  description: "Draco 3D Data Compression Unity Package "
  labels:
    costcenter: "2212"
  tags:
    - planned-public
    - enterprise
spec:
  type: unity-package
  lifecycle: production
  owner: unity/digital-twins-sdk-admins
  